spring:
  devtools:
    restart:
      enabled: false
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    timeout: 6000    #连接超时时长（毫秒）
    jedis:
      pool:
        max-active: 1000
        max-idle: 10
        min-idle: 5
        max-wait: -1
server:
  port: 90
